# Generated by Django 5.0.13 on 2025-12-09 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_diagnostico', models.CharField(max_length=255)),
                ('descripcion_corta', models.TextField()),
                ('cie_10_codigo', models.CharField(max_length=20)),
                ('dsm_5_codigo', models.CharField(max_length=20)),
                ('tratamientos_sugeridos', models.TextField()),
                ('es_cronico', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PacientePsicologia',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('motivo_consulta_inicial', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id_psicologo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('licencia_colegiado', models.CharField(max_length=50)),
                ('enfoque_terapeutico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoPsicologico',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_recurso', models.CharField(max_length=255)),
                ('tipo_recurso', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('url_recurso', models.CharField(max_length=255)),
                ('tema_principal', models.CharField(max_length=100)),
                ('publico_objetivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaPsicologia',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('id_sesion_asociada', models.IntegerField()),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.pacientepsicologia')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinicoPsicologia',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('antecedentes_familiares', models.TextField()),
                ('antecedentes_personales', models.TextField()),
                ('medicamentos_actuales', models.TextField()),
                ('resumen_evolucion', models.TextField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.pacientepsicologia')),
                ('id_psicologo_tratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.psicologo')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sesion', models.DateTimeField()),
                ('hora_sesion', models.TimeField()),
                ('tipo_sesion', models.CharField(max_length=50)),
                ('duracion_minutos', models.IntegerField()),
                ('notas_sesion', models.TextField()),
                ('diagnostico_actual', models.TextField()),
                ('costo_sesion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.pacientepsicologia')),
                ('id_psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.psicologo')),
            ],
        ),
    ]
