# Generated by Django 5.0.13 on 2025-12-09 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoInformadoPsicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('consentimiento', models.TextField()),
                ('firma_paciente', models.ImageField(blank=True, null=True, upload_to='firmas/')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentimientoInformadoPsicopedagogia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('texto', models.TextField()),
                ('firma_tutor', models.ImageField(blank=True, null=True, upload_to='firmas/')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionPsicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionPsicopedagogia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('intervencion', models.TextField()),
                ('evolucion', models.TextField()),
                ('objetivos_proxima', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinicaPsicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('antecedentes_personales', models.TextField()),
                ('antecedentes_familiares', models.TextField()),
                ('examen_mental', models.TextField()),
                ('diagnostico_presuntivo', models.TextField()),
                ('plan_terapeutico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinicaPsicopedagogia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('historia_escolar', models.TextField()),
                ('desarrollo_motor', models.TextField()),
                ('desarrollo_lenguaje', models.TextField()),
                ('area_socio_afectiva', models.TextField()),
                ('diagnostico', models.TextField()),
                ('sugerencias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('obra_social', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('profesional', models.CharField(max_length=100)),
                ('asistio', models.BooleanField(default=False)),
                ('motivo_consulta', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Diagnostico',
        ),
        migrations.RemoveField(
            model_name='facturapsicologia',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='historialclinicopsicologia',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='historialclinicopsicologia',
            name='id_psicologo_tratante',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='id_psicologo',
        ),
        migrations.DeleteModel(
            name='RecursoPsicologico',
        ),
        migrations.AddField(
            model_name='evolucionpsicologia',
            name='historia_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.historiaclinicapsicologia'),
        ),
        migrations.AddField(
            model_name='evolucionpsicopedagogia',
            name='historia_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.historiaclinicapsicopedagogia'),
        ),
        migrations.AddField(
            model_name='historiaclinicapsicopedagogia',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente'),
        ),
        migrations.AddField(
            model_name='historiaclinicapsicologia',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente'),
        ),
        migrations.AddField(
            model_name='consentimientoinformadopsicopedagogia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente'),
        ),
        migrations.AddField(
            model_name='consentimientoinformadopsicologia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente'),
        ),
        migrations.DeleteModel(
            name='FacturaPsicologia',
        ),
        migrations.DeleteModel(
            name='HistorialClinicoPsicologia',
        ),
        migrations.DeleteModel(
            name='PacientePsicologia',
        ),
        migrations.DeleteModel(
            name='Psicologo',
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
    ]
